
server {
    listen 443 default_server;
    server_name 13.60.24.46;

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location /static/ {
        alias /home/ubuntu/project-pfe-space/api/staticfiles/;
    }

    location /media/ {
        alias /home/ubuntu/project-pfe-space/api/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}