# Generated by Django 6.0.2 on 2026-02-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSERule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('epi_type', models.CharField(choices=[('hardhat', 'Casque'), ('safety_vest', 'Gilet'), ('mask', 'Masque'), ('gloves', 'Gants'), ('safety_glasses', 'Lunettes'), ('ear_protection', 'Protection auditive')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('cameras', models.ManyToManyField(blank=True, related_name='hse_rules', to='Cameras.camera')),
            ],
        ),
    ]
