# Generated by Django 6.0.2 on 2026-02-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegleSHE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hserule',
            name='epi_criticites',
            field=models.JSONField(blank=True, default=list, help_text="Liste d'objets {epi: str, criticite: str}"),
        ),
    ]
