# Generated by Django 6.0.2 on 2026-02-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegleSHE', '0002_hserule_epi_criticites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hserule',
            name='epi_type',
            field=models.CharField(blank=True, choices=[('hardhat', 'Casque'), ('safety_vest', 'Gilet'), ('mask', 'Masque'), ('gloves', 'Gants'), ('safety_glasses', 'Lunettes'), ('ear_protection', 'Protection auditive')], max_length=32, null=True),
        ),
    ]
