# Generated by Django 6.0.2 on 2026-02-17 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detections_json', models.JSONField(default=list)),
                ('stats_json', models.JSONField(default=dict)),
                ('is_compliant', models.BooleanField(default=True)),
                ('processing_time', models.FloatField(default=0.0)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_logs', to='Cameras.camera')),
            ],
            options={
                'verbose_name': 'Log de détection',
                'verbose_name_plural': 'Logs de détection',
                'ordering': ['-timestamp'],
            },
        ),
    ]
