# Generated by Django 6.0.4 on 2026-05-04 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cameras', '0001_initial'),
        ('alertes', '0002_alert_first_acknowledged_at'),
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonComplianceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=255)),
                ('missing_epi', models.JSONField(default=list)),
                ('first_detected_at', models.DateTimeField()),
                ('last_detected_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('queued_for_llm', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_compliance_states', to='Cameras.camera')),
                ('last_seen_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_non_compliance_states', to='detection.detectionlog')),
            ],
            options={
                'verbose_name': 'État de non-conformité persistante',
                'verbose_name_plural': 'États de non-conformité persistante',
                'ordering': ['-last_detected_at'],
            },
        ),
        migrations.CreateModel(
            name='GeminiContextAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gemini/context/')),
                ('missing_epi', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', 'En file'), ('processing', 'En traitement'), ('completed', 'Terminée'), ('failed', 'Échouée'), ('quota_skipped', 'Quota dépassé')], default='queued', max_length=20)),
                ('request_reason', models.CharField(blank=True, max_length=255)),
                ('prompt', models.TextField(blank=True)),
                ('response_text', models.TextField(blank=True)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('action', models.CharField(blank=True, choices=[('ALERT', 'Alert'), ('MONITOR', 'Monitor'), ('OK', 'OK')], max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('llm_confidence', models.FloatField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemini_analyses', to='alertes.alert')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemini_analyses', to='Cameras.camera')),
                ('detection_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemini_analyses', to='detection.detectionlog')),
                ('non_compliance_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemini_analyses', to='detection.noncompliancestate')),
            ],
            options={
                'verbose_name': 'Analyse contextuelle Gemini',
                'verbose_name_plural': 'Analyses contextuelles Gemini',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='noncompliancestate',
            index=models.Index(fields=['camera', 'signature', 'is_active'], name='detection_n_camera__a88dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='geminicontextanalysis',
            index=models.Index(fields=['status', 'requested_at'], name='detection_g_status_c913b4_idx'),
        ),
        migrations.AddIndex(
            model_name='geminicontextanalysis',
            index=models.Index(fields=['camera', 'requested_at'], name='detection_g_camera__93b8ae_idx'),
        ),
    ]
