# Generated by Django 6.0.2 on 2026-02-17 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cameras', '0001_initial'),
        ('alertes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('clos', 'Clos')], default='ouvert', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='alertes.alert')),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='Cameras.camera')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='audits/captures/')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='audits.audit')),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Capture d'audit",
                'verbose_name_plural': "Captures d'audit",
                'ordering': ['-taken_at'],
            },
        ),
    ]
